// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

package handlers_test

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/screamsoul/go-metrics-tpl/internal/models/metrics"
)

// MetricStorageMock implements repositories.MetricStorage
type MetricStorageMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcAdd          func(ctx context.Context, m metrics.Metrics) (err error)
	inspectFuncAdd   func(ctx context.Context, m metrics.Metrics)
	afterAddCounter  uint64
	beforeAddCounter uint64
	AddMock          mMetricStorageMockAdd

	funcBulkAdd          func(ctx context.Context, m []metrics.Metrics) (err error)
	inspectFuncBulkAdd   func(ctx context.Context, m []metrics.Metrics)
	afterBulkAddCounter  uint64
	beforeBulkAddCounter uint64
	BulkAddMock          mMetricStorageMockBulkAdd

	funcGet          func(ctx context.Context, m *metrics.Metrics) (err error)
	inspectFuncGet   func(ctx context.Context, m *metrics.Metrics)
	afterGetCounter  uint64
	beforeGetCounter uint64
	GetMock          mMetricStorageMockGet

	funcList          func(ctx context.Context) (ma1 []metrics.Metrics, err error)
	inspectFuncList   func(ctx context.Context)
	afterListCounter  uint64
	beforeListCounter uint64
	ListMock          mMetricStorageMockList

	funcPing          func(ctx context.Context) (b1 bool)
	inspectFuncPing   func(ctx context.Context)
	afterPingCounter  uint64
	beforePingCounter uint64
	PingMock          mMetricStorageMockPing
}

// NewMetricStorageMock returns a mock for repositories.MetricStorage
func NewMetricStorageMock(t minimock.Tester) *MetricStorageMock {
	m := &MetricStorageMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.AddMock = mMetricStorageMockAdd{mock: m}
	m.AddMock.callArgs = []*MetricStorageMockAddParams{}

	m.BulkAddMock = mMetricStorageMockBulkAdd{mock: m}
	m.BulkAddMock.callArgs = []*MetricStorageMockBulkAddParams{}

	m.GetMock = mMetricStorageMockGet{mock: m}
	m.GetMock.callArgs = []*MetricStorageMockGetParams{}

	m.ListMock = mMetricStorageMockList{mock: m}
	m.ListMock.callArgs = []*MetricStorageMockListParams{}

	m.PingMock = mMetricStorageMockPing{mock: m}
	m.PingMock.callArgs = []*MetricStorageMockPingParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mMetricStorageMockAdd struct {
	mock               *MetricStorageMock
	defaultExpectation *MetricStorageMockAddExpectation
	expectations       []*MetricStorageMockAddExpectation

	callArgs []*MetricStorageMockAddParams
	mutex    sync.RWMutex
}

// MetricStorageMockAddExpectation specifies expectation struct of the MetricStorage.Add
type MetricStorageMockAddExpectation struct {
	mock    *MetricStorageMock
	params  *MetricStorageMockAddParams
	results *MetricStorageMockAddResults
	Counter uint64
}

// MetricStorageMockAddParams contains parameters of the MetricStorage.Add
type MetricStorageMockAddParams struct {
	ctx context.Context
	m   metrics.Metrics
}

// MetricStorageMockAddResults contains results of the MetricStorage.Add
type MetricStorageMockAddResults struct {
	err error
}

// Expect sets up expected params for MetricStorage.Add
func (mmAdd *mMetricStorageMockAdd) Expect(ctx context.Context, m metrics.Metrics) *mMetricStorageMockAdd {
	if mmAdd.mock.funcAdd != nil {
		mmAdd.mock.t.Fatalf("MetricStorageMock.Add mock is already set by Set")
	}

	if mmAdd.defaultExpectation == nil {
		mmAdd.defaultExpectation = &MetricStorageMockAddExpectation{}
	}

	mmAdd.defaultExpectation.params = &MetricStorageMockAddParams{ctx, m}
	for _, e := range mmAdd.expectations {
		if minimock.Equal(e.params, mmAdd.defaultExpectation.params) {
			mmAdd.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmAdd.defaultExpectation.params)
		}
	}

	return mmAdd
}

// Inspect accepts an inspector function that has same arguments as the MetricStorage.Add
func (mmAdd *mMetricStorageMockAdd) Inspect(f func(ctx context.Context, m metrics.Metrics)) *mMetricStorageMockAdd {
	if mmAdd.mock.inspectFuncAdd != nil {
		mmAdd.mock.t.Fatalf("Inspect function is already set for MetricStorageMock.Add")
	}

	mmAdd.mock.inspectFuncAdd = f

	return mmAdd
}

// Return sets up results that will be returned by MetricStorage.Add
func (mmAdd *mMetricStorageMockAdd) Return(err error) *MetricStorageMock {
	if mmAdd.mock.funcAdd != nil {
		mmAdd.mock.t.Fatalf("MetricStorageMock.Add mock is already set by Set")
	}

	if mmAdd.defaultExpectation == nil {
		mmAdd.defaultExpectation = &MetricStorageMockAddExpectation{mock: mmAdd.mock}
	}
	mmAdd.defaultExpectation.results = &MetricStorageMockAddResults{err}
	return mmAdd.mock
}

// Set uses given function f to mock the MetricStorage.Add method
func (mmAdd *mMetricStorageMockAdd) Set(f func(ctx context.Context, m metrics.Metrics) (err error)) *MetricStorageMock {
	if mmAdd.defaultExpectation != nil {
		mmAdd.mock.t.Fatalf("Default expectation is already set for the MetricStorage.Add method")
	}

	if len(mmAdd.expectations) > 0 {
		mmAdd.mock.t.Fatalf("Some expectations are already set for the MetricStorage.Add method")
	}

	mmAdd.mock.funcAdd = f
	return mmAdd.mock
}

// When sets expectation for the MetricStorage.Add which will trigger the result defined by the following
// Then helper
func (mmAdd *mMetricStorageMockAdd) When(ctx context.Context, m metrics.Metrics) *MetricStorageMockAddExpectation {
	if mmAdd.mock.funcAdd != nil {
		mmAdd.mock.t.Fatalf("MetricStorageMock.Add mock is already set by Set")
	}

	expectation := &MetricStorageMockAddExpectation{
		mock:   mmAdd.mock,
		params: &MetricStorageMockAddParams{ctx, m},
	}
	mmAdd.expectations = append(mmAdd.expectations, expectation)
	return expectation
}

// Then sets up MetricStorage.Add return parameters for the expectation previously defined by the When method
func (e *MetricStorageMockAddExpectation) Then(err error) *MetricStorageMock {
	e.results = &MetricStorageMockAddResults{err}
	return e.mock
}

// Add implements repositories.MetricStorage
func (mmAdd *MetricStorageMock) Add(ctx context.Context, m metrics.Metrics) (err error) {
	mm_atomic.AddUint64(&mmAdd.beforeAddCounter, 1)
	defer mm_atomic.AddUint64(&mmAdd.afterAddCounter, 1)

	if mmAdd.inspectFuncAdd != nil {
		mmAdd.inspectFuncAdd(ctx, m)
	}

	mm_params := MetricStorageMockAddParams{ctx, m}

	// Record call args
	mmAdd.AddMock.mutex.Lock()
	mmAdd.AddMock.callArgs = append(mmAdd.AddMock.callArgs, &mm_params)
	mmAdd.AddMock.mutex.Unlock()

	for _, e := range mmAdd.AddMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmAdd.AddMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmAdd.AddMock.defaultExpectation.Counter, 1)
		mm_want := mmAdd.AddMock.defaultExpectation.params
		mm_got := MetricStorageMockAddParams{ctx, m}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmAdd.t.Errorf("MetricStorageMock.Add got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmAdd.AddMock.defaultExpectation.results
		if mm_results != nil {
			return (*mm_results).err
		}
		mmAdd.t.Fatal("No results are set for the MetricStorageMock.Add")

	}
	if mmAdd.funcAdd != nil {
		return mmAdd.funcAdd(ctx, m)
	}
	mmAdd.t.Fatalf("Unexpected call to MetricStorageMock.Add. %v %v", ctx, m)
	return
}

// AddAfterCounter returns a count of finished MetricStorageMock.Add invocations
func (mmAdd *MetricStorageMock) AddAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAdd.afterAddCounter)
}

// AddBeforeCounter returns a count of MetricStorageMock.Add invocations
func (mmAdd *MetricStorageMock) AddBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAdd.beforeAddCounter)
}

// Calls returns a list of arguments used in each call to MetricStorageMock.Add.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmAdd *mMetricStorageMockAdd) Calls() []*MetricStorageMockAddParams {
	mmAdd.mutex.RLock()

	argCopy := make([]*MetricStorageMockAddParams, len(mmAdd.callArgs))
	copy(argCopy, mmAdd.callArgs)

	mmAdd.mutex.RUnlock()

	return argCopy
}

// MinimockAddDone returns true if the count of the Add invocations corresponds
// the number of defined expectations
func (m *MetricStorageMock) MinimockAddDone() bool {
	for _, e := range m.AddMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.AddMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterAddCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcAdd != nil && mm_atomic.LoadUint64(&m.afterAddCounter) < 1 {
		return false
	}
	return true
}

// MinimockAddInspect logs each unmet expectation
func (m *MetricStorageMock) MinimockAddInspect() {
	for _, e := range m.AddMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to MetricStorageMock.Add with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.AddMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterAddCounter) < 1 {
		if m.AddMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to MetricStorageMock.Add")
		} else {
			m.t.Errorf("Expected call to MetricStorageMock.Add with params: %#v", *m.AddMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcAdd != nil && mm_atomic.LoadUint64(&m.afterAddCounter) < 1 {
		m.t.Error("Expected call to MetricStorageMock.Add")
	}
}

type mMetricStorageMockBulkAdd struct {
	mock               *MetricStorageMock
	defaultExpectation *MetricStorageMockBulkAddExpectation
	expectations       []*MetricStorageMockBulkAddExpectation

	callArgs []*MetricStorageMockBulkAddParams
	mutex    sync.RWMutex
}

// MetricStorageMockBulkAddExpectation specifies expectation struct of the MetricStorage.BulkAdd
type MetricStorageMockBulkAddExpectation struct {
	mock    *MetricStorageMock
	params  *MetricStorageMockBulkAddParams
	results *MetricStorageMockBulkAddResults
	Counter uint64
}

// MetricStorageMockBulkAddParams contains parameters of the MetricStorage.BulkAdd
type MetricStorageMockBulkAddParams struct {
	ctx context.Context
	m   []metrics.Metrics
}

// MetricStorageMockBulkAddResults contains results of the MetricStorage.BulkAdd
type MetricStorageMockBulkAddResults struct {
	err error
}

// Expect sets up expected params for MetricStorage.BulkAdd
func (mmBulkAdd *mMetricStorageMockBulkAdd) Expect(ctx context.Context, m []metrics.Metrics) *mMetricStorageMockBulkAdd {
	if mmBulkAdd.mock.funcBulkAdd != nil {
		mmBulkAdd.mock.t.Fatalf("MetricStorageMock.BulkAdd mock is already set by Set")
	}

	if mmBulkAdd.defaultExpectation == nil {
		mmBulkAdd.defaultExpectation = &MetricStorageMockBulkAddExpectation{}
	}

	mmBulkAdd.defaultExpectation.params = &MetricStorageMockBulkAddParams{ctx, m}
	for _, e := range mmBulkAdd.expectations {
		if minimock.Equal(e.params, mmBulkAdd.defaultExpectation.params) {
			mmBulkAdd.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmBulkAdd.defaultExpectation.params)
		}
	}

	return mmBulkAdd
}

// Inspect accepts an inspector function that has same arguments as the MetricStorage.BulkAdd
func (mmBulkAdd *mMetricStorageMockBulkAdd) Inspect(f func(ctx context.Context, m []metrics.Metrics)) *mMetricStorageMockBulkAdd {
	if mmBulkAdd.mock.inspectFuncBulkAdd != nil {
		mmBulkAdd.mock.t.Fatalf("Inspect function is already set for MetricStorageMock.BulkAdd")
	}

	mmBulkAdd.mock.inspectFuncBulkAdd = f

	return mmBulkAdd
}

// Return sets up results that will be returned by MetricStorage.BulkAdd
func (mmBulkAdd *mMetricStorageMockBulkAdd) Return(err error) *MetricStorageMock {
	if mmBulkAdd.mock.funcBulkAdd != nil {
		mmBulkAdd.mock.t.Fatalf("MetricStorageMock.BulkAdd mock is already set by Set")
	}

	if mmBulkAdd.defaultExpectation == nil {
		mmBulkAdd.defaultExpectation = &MetricStorageMockBulkAddExpectation{mock: mmBulkAdd.mock}
	}
	mmBulkAdd.defaultExpectation.results = &MetricStorageMockBulkAddResults{err}
	return mmBulkAdd.mock
}

// Set uses given function f to mock the MetricStorage.BulkAdd method
func (mmBulkAdd *mMetricStorageMockBulkAdd) Set(f func(ctx context.Context, m []metrics.Metrics) (err error)) *MetricStorageMock {
	if mmBulkAdd.defaultExpectation != nil {
		mmBulkAdd.mock.t.Fatalf("Default expectation is already set for the MetricStorage.BulkAdd method")
	}

	if len(mmBulkAdd.expectations) > 0 {
		mmBulkAdd.mock.t.Fatalf("Some expectations are already set for the MetricStorage.BulkAdd method")
	}

	mmBulkAdd.mock.funcBulkAdd = f
	return mmBulkAdd.mock
}

// When sets expectation for the MetricStorage.BulkAdd which will trigger the result defined by the following
// Then helper
func (mmBulkAdd *mMetricStorageMockBulkAdd) When(ctx context.Context, m []metrics.Metrics) *MetricStorageMockBulkAddExpectation {
	if mmBulkAdd.mock.funcBulkAdd != nil {
		mmBulkAdd.mock.t.Fatalf("MetricStorageMock.BulkAdd mock is already set by Set")
	}

	expectation := &MetricStorageMockBulkAddExpectation{
		mock:   mmBulkAdd.mock,
		params: &MetricStorageMockBulkAddParams{ctx, m},
	}
	mmBulkAdd.expectations = append(mmBulkAdd.expectations, expectation)
	return expectation
}

// Then sets up MetricStorage.BulkAdd return parameters for the expectation previously defined by the When method
func (e *MetricStorageMockBulkAddExpectation) Then(err error) *MetricStorageMock {
	e.results = &MetricStorageMockBulkAddResults{err}
	return e.mock
}

// BulkAdd implements repositories.MetricStorage
func (mmBulkAdd *MetricStorageMock) BulkAdd(ctx context.Context, m []metrics.Metrics) (err error) {
	mm_atomic.AddUint64(&mmBulkAdd.beforeBulkAddCounter, 1)
	defer mm_atomic.AddUint64(&mmBulkAdd.afterBulkAddCounter, 1)

	if mmBulkAdd.inspectFuncBulkAdd != nil {
		mmBulkAdd.inspectFuncBulkAdd(ctx, m)
	}

	mm_params := MetricStorageMockBulkAddParams{ctx, m}

	// Record call args
	mmBulkAdd.BulkAddMock.mutex.Lock()
	mmBulkAdd.BulkAddMock.callArgs = append(mmBulkAdd.BulkAddMock.callArgs, &mm_params)
	mmBulkAdd.BulkAddMock.mutex.Unlock()

	for _, e := range mmBulkAdd.BulkAddMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmBulkAdd.BulkAddMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmBulkAdd.BulkAddMock.defaultExpectation.Counter, 1)
		mm_want := mmBulkAdd.BulkAddMock.defaultExpectation.params
		mm_got := MetricStorageMockBulkAddParams{ctx, m}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmBulkAdd.t.Errorf("MetricStorageMock.BulkAdd got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmBulkAdd.BulkAddMock.defaultExpectation.results
		if mm_results != nil {
			return (*mm_results).err
		}
		mmBulkAdd.t.Fatal("No results are set for the MetricStorageMock.BulkAdd")

	}
	if mmBulkAdd.funcBulkAdd != nil {
		return mmBulkAdd.funcBulkAdd(ctx, m)
	}
	mmBulkAdd.t.Fatalf("Unexpected call to MetricStorageMock.BulkAdd. %v %v", ctx, m)
	return
}

// BulkAddAfterCounter returns a count of finished MetricStorageMock.BulkAdd invocations
func (mmBulkAdd *MetricStorageMock) BulkAddAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmBulkAdd.afterBulkAddCounter)
}

// BulkAddBeforeCounter returns a count of MetricStorageMock.BulkAdd invocations
func (mmBulkAdd *MetricStorageMock) BulkAddBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmBulkAdd.beforeBulkAddCounter)
}

// Calls returns a list of arguments used in each call to MetricStorageMock.BulkAdd.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmBulkAdd *mMetricStorageMockBulkAdd) Calls() []*MetricStorageMockBulkAddParams {
	mmBulkAdd.mutex.RLock()

	argCopy := make([]*MetricStorageMockBulkAddParams, len(mmBulkAdd.callArgs))
	copy(argCopy, mmBulkAdd.callArgs)

	mmBulkAdd.mutex.RUnlock()

	return argCopy
}

// MinimockBulkAddDone returns true if the count of the BulkAdd invocations corresponds
// the number of defined expectations
func (m *MetricStorageMock) MinimockBulkAddDone() bool {
	for _, e := range m.BulkAddMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.BulkAddMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterBulkAddCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcBulkAdd != nil && mm_atomic.LoadUint64(&m.afterBulkAddCounter) < 1 {
		return false
	}
	return true
}

// MinimockBulkAddInspect logs each unmet expectation
func (m *MetricStorageMock) MinimockBulkAddInspect() {
	for _, e := range m.BulkAddMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to MetricStorageMock.BulkAdd with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.BulkAddMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterBulkAddCounter) < 1 {
		if m.BulkAddMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to MetricStorageMock.BulkAdd")
		} else {
			m.t.Errorf("Expected call to MetricStorageMock.BulkAdd with params: %#v", *m.BulkAddMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcBulkAdd != nil && mm_atomic.LoadUint64(&m.afterBulkAddCounter) < 1 {
		m.t.Error("Expected call to MetricStorageMock.BulkAdd")
	}
}

type mMetricStorageMockGet struct {
	mock               *MetricStorageMock
	defaultExpectation *MetricStorageMockGetExpectation
	expectations       []*MetricStorageMockGetExpectation

	callArgs []*MetricStorageMockGetParams
	mutex    sync.RWMutex
}

// MetricStorageMockGetExpectation specifies expectation struct of the MetricStorage.Get
type MetricStorageMockGetExpectation struct {
	mock    *MetricStorageMock
	params  *MetricStorageMockGetParams
	results *MetricStorageMockGetResults
	Counter uint64
}

// MetricStorageMockGetParams contains parameters of the MetricStorage.Get
type MetricStorageMockGetParams struct {
	ctx context.Context
	m   *metrics.Metrics
}

// MetricStorageMockGetResults contains results of the MetricStorage.Get
type MetricStorageMockGetResults struct {
	err error
}

// Expect sets up expected params for MetricStorage.Get
func (mmGet *mMetricStorageMockGet) Expect(ctx context.Context, m *metrics.Metrics) *mMetricStorageMockGet {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("MetricStorageMock.Get mock is already set by Set")
	}

	if mmGet.defaultExpectation == nil {
		mmGet.defaultExpectation = &MetricStorageMockGetExpectation{}
	}

	mmGet.defaultExpectation.params = &MetricStorageMockGetParams{ctx, m}
	for _, e := range mmGet.expectations {
		if minimock.Equal(e.params, mmGet.defaultExpectation.params) {
			mmGet.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGet.defaultExpectation.params)
		}
	}

	return mmGet
}

// Inspect accepts an inspector function that has same arguments as the MetricStorage.Get
func (mmGet *mMetricStorageMockGet) Inspect(f func(ctx context.Context, m *metrics.Metrics)) *mMetricStorageMockGet {
	if mmGet.mock.inspectFuncGet != nil {
		mmGet.mock.t.Fatalf("Inspect function is already set for MetricStorageMock.Get")
	}

	mmGet.mock.inspectFuncGet = f

	return mmGet
}

// Return sets up results that will be returned by MetricStorage.Get
func (mmGet *mMetricStorageMockGet) Return(err error) *MetricStorageMock {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("MetricStorageMock.Get mock is already set by Set")
	}

	if mmGet.defaultExpectation == nil {
		mmGet.defaultExpectation = &MetricStorageMockGetExpectation{mock: mmGet.mock}
	}
	mmGet.defaultExpectation.results = &MetricStorageMockGetResults{err}
	return mmGet.mock
}

// Set uses given function f to mock the MetricStorage.Get method
func (mmGet *mMetricStorageMockGet) Set(f func(ctx context.Context, m *metrics.Metrics) (err error)) *MetricStorageMock {
	if mmGet.defaultExpectation != nil {
		mmGet.mock.t.Fatalf("Default expectation is already set for the MetricStorage.Get method")
	}

	if len(mmGet.expectations) > 0 {
		mmGet.mock.t.Fatalf("Some expectations are already set for the MetricStorage.Get method")
	}

	mmGet.mock.funcGet = f
	return mmGet.mock
}

// When sets expectation for the MetricStorage.Get which will trigger the result defined by the following
// Then helper
func (mmGet *mMetricStorageMockGet) When(ctx context.Context, m *metrics.Metrics) *MetricStorageMockGetExpectation {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("MetricStorageMock.Get mock is already set by Set")
	}

	expectation := &MetricStorageMockGetExpectation{
		mock:   mmGet.mock,
		params: &MetricStorageMockGetParams{ctx, m},
	}
	mmGet.expectations = append(mmGet.expectations, expectation)
	return expectation
}

// Then sets up MetricStorage.Get return parameters for the expectation previously defined by the When method
func (e *MetricStorageMockGetExpectation) Then(err error) *MetricStorageMock {
	e.results = &MetricStorageMockGetResults{err}
	return e.mock
}

// Get implements repositories.MetricStorage
func (mmGet *MetricStorageMock) Get(ctx context.Context, m *metrics.Metrics) (err error) {
	mm_atomic.AddUint64(&mmGet.beforeGetCounter, 1)
	defer mm_atomic.AddUint64(&mmGet.afterGetCounter, 1)

	if mmGet.inspectFuncGet != nil {
		mmGet.inspectFuncGet(ctx, m)
	}

	mm_params := MetricStorageMockGetParams{ctx, m}

	// Record call args
	mmGet.GetMock.mutex.Lock()
	mmGet.GetMock.callArgs = append(mmGet.GetMock.callArgs, &mm_params)
	mmGet.GetMock.mutex.Unlock()

	for _, e := range mmGet.GetMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmGet.GetMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGet.GetMock.defaultExpectation.Counter, 1)
		mm_want := mmGet.GetMock.defaultExpectation.params
		mm_got := MetricStorageMockGetParams{ctx, m}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGet.t.Errorf("MetricStorageMock.Get got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGet.GetMock.defaultExpectation.results
		if mm_results != nil {
			return (*mm_results).err
		}
		mmGet.t.Fatal("No results are set for the MetricStorageMock.Get")

	}
	if mmGet.funcGet != nil {
		return mmGet.funcGet(ctx, m)
	}
	mmGet.t.Fatalf("Unexpected call to MetricStorageMock.Get. %v %v", ctx, m)
	return
}

// GetAfterCounter returns a count of finished MetricStorageMock.Get invocations
func (mmGet *MetricStorageMock) GetAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGet.afterGetCounter)
}

// GetBeforeCounter returns a count of MetricStorageMock.Get invocations
func (mmGet *MetricStorageMock) GetBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGet.beforeGetCounter)
}

// Calls returns a list of arguments used in each call to MetricStorageMock.Get.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGet *mMetricStorageMockGet) Calls() []*MetricStorageMockGetParams {
	mmGet.mutex.RLock()

	argCopy := make([]*MetricStorageMockGetParams, len(mmGet.callArgs))
	copy(argCopy, mmGet.callArgs)

	mmGet.mutex.RUnlock()

	return argCopy
}

// MinimockGetDone returns true if the count of the Get invocations corresponds
// the number of defined expectations
func (m *MetricStorageMock) MinimockGetDone() bool {
	for _, e := range m.GetMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.GetMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterGetCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGet != nil && mm_atomic.LoadUint64(&m.afterGetCounter) < 1 {
		return false
	}
	return true
}

// MinimockGetInspect logs each unmet expectation
func (m *MetricStorageMock) MinimockGetInspect() {
	for _, e := range m.GetMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to MetricStorageMock.Get with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.GetMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterGetCounter) < 1 {
		if m.GetMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to MetricStorageMock.Get")
		} else {
			m.t.Errorf("Expected call to MetricStorageMock.Get with params: %#v", *m.GetMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGet != nil && mm_atomic.LoadUint64(&m.afterGetCounter) < 1 {
		m.t.Error("Expected call to MetricStorageMock.Get")
	}
}

type mMetricStorageMockList struct {
	mock               *MetricStorageMock
	defaultExpectation *MetricStorageMockListExpectation
	expectations       []*MetricStorageMockListExpectation

	callArgs []*MetricStorageMockListParams
	mutex    sync.RWMutex
}

// MetricStorageMockListExpectation specifies expectation struct of the MetricStorage.List
type MetricStorageMockListExpectation struct {
	mock    *MetricStorageMock
	params  *MetricStorageMockListParams
	results *MetricStorageMockListResults
	Counter uint64
}

// MetricStorageMockListParams contains parameters of the MetricStorage.List
type MetricStorageMockListParams struct {
	ctx context.Context
}

// MetricStorageMockListResults contains results of the MetricStorage.List
type MetricStorageMockListResults struct {
	ma1 []metrics.Metrics
	err error
}

// Expect sets up expected params for MetricStorage.List
func (mmList *mMetricStorageMockList) Expect(ctx context.Context) *mMetricStorageMockList {
	if mmList.mock.funcList != nil {
		mmList.mock.t.Fatalf("MetricStorageMock.List mock is already set by Set")
	}

	if mmList.defaultExpectation == nil {
		mmList.defaultExpectation = &MetricStorageMockListExpectation{}
	}

	mmList.defaultExpectation.params = &MetricStorageMockListParams{ctx}
	for _, e := range mmList.expectations {
		if minimock.Equal(e.params, mmList.defaultExpectation.params) {
			mmList.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmList.defaultExpectation.params)
		}
	}

	return mmList
}

// Inspect accepts an inspector function that has same arguments as the MetricStorage.List
func (mmList *mMetricStorageMockList) Inspect(f func(ctx context.Context)) *mMetricStorageMockList {
	if mmList.mock.inspectFuncList != nil {
		mmList.mock.t.Fatalf("Inspect function is already set for MetricStorageMock.List")
	}

	mmList.mock.inspectFuncList = f

	return mmList
}

// Return sets up results that will be returned by MetricStorage.List
func (mmList *mMetricStorageMockList) Return(ma1 []metrics.Metrics, err error) *MetricStorageMock {
	if mmList.mock.funcList != nil {
		mmList.mock.t.Fatalf("MetricStorageMock.List mock is already set by Set")
	}

	if mmList.defaultExpectation == nil {
		mmList.defaultExpectation = &MetricStorageMockListExpectation{mock: mmList.mock}
	}
	mmList.defaultExpectation.results = &MetricStorageMockListResults{ma1, err}
	return mmList.mock
}

// Set uses given function f to mock the MetricStorage.List method
func (mmList *mMetricStorageMockList) Set(f func(ctx context.Context) (ma1 []metrics.Metrics, err error)) *MetricStorageMock {
	if mmList.defaultExpectation != nil {
		mmList.mock.t.Fatalf("Default expectation is already set for the MetricStorage.List method")
	}

	if len(mmList.expectations) > 0 {
		mmList.mock.t.Fatalf("Some expectations are already set for the MetricStorage.List method")
	}

	mmList.mock.funcList = f
	return mmList.mock
}

// When sets expectation for the MetricStorage.List which will trigger the result defined by the following
// Then helper
func (mmList *mMetricStorageMockList) When(ctx context.Context) *MetricStorageMockListExpectation {
	if mmList.mock.funcList != nil {
		mmList.mock.t.Fatalf("MetricStorageMock.List mock is already set by Set")
	}

	expectation := &MetricStorageMockListExpectation{
		mock:   mmList.mock,
		params: &MetricStorageMockListParams{ctx},
	}
	mmList.expectations = append(mmList.expectations, expectation)
	return expectation
}

// Then sets up MetricStorage.List return parameters for the expectation previously defined by the When method
func (e *MetricStorageMockListExpectation) Then(ma1 []metrics.Metrics, err error) *MetricStorageMock {
	e.results = &MetricStorageMockListResults{ma1, err}
	return e.mock
}

// List implements repositories.MetricStorage
func (mmList *MetricStorageMock) List(ctx context.Context) (ma1 []metrics.Metrics, err error) {
	mm_atomic.AddUint64(&mmList.beforeListCounter, 1)
	defer mm_atomic.AddUint64(&mmList.afterListCounter, 1)

	if mmList.inspectFuncList != nil {
		mmList.inspectFuncList(ctx)
	}

	mm_params := MetricStorageMockListParams{ctx}

	// Record call args
	mmList.ListMock.mutex.Lock()
	mmList.ListMock.callArgs = append(mmList.ListMock.callArgs, &mm_params)
	mmList.ListMock.mutex.Unlock()

	for _, e := range mmList.ListMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ma1, e.results.err
		}
	}

	if mmList.ListMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmList.ListMock.defaultExpectation.Counter, 1)
		mm_want := mmList.ListMock.defaultExpectation.params
		mm_got := MetricStorageMockListParams{ctx}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmList.t.Errorf("MetricStorageMock.List got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmList.ListMock.defaultExpectation.results
		if mm_results != nil {
			return (*mm_results).ma1, (*mm_results).err
		}
		mmList.t.Fatal("No results are set for the MetricStorageMock.List")

	}
	if mmList.funcList != nil {
		return mmList.funcList(ctx)
	}
	mmList.t.Fatalf("Unexpected call to MetricStorageMock.List. %v", ctx)
	return
}

// ListAfterCounter returns a count of finished MetricStorageMock.List invocations
func (mmList *MetricStorageMock) ListAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmList.afterListCounter)
}

// ListBeforeCounter returns a count of MetricStorageMock.List invocations
func (mmList *MetricStorageMock) ListBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmList.beforeListCounter)
}

// Calls returns a list of arguments used in each call to MetricStorageMock.List.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmList *mMetricStorageMockList) Calls() []*MetricStorageMockListParams {
	mmList.mutex.RLock()

	argCopy := make([]*MetricStorageMockListParams, len(mmList.callArgs))
	copy(argCopy, mmList.callArgs)

	mmList.mutex.RUnlock()

	return argCopy
}

// MinimockListDone returns true if the count of the List invocations corresponds
// the number of defined expectations
func (m *MetricStorageMock) MinimockListDone() bool {
	for _, e := range m.ListMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.ListMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterListCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcList != nil && mm_atomic.LoadUint64(&m.afterListCounter) < 1 {
		return false
	}
	return true
}

// MinimockListInspect logs each unmet expectation
func (m *MetricStorageMock) MinimockListInspect() {
	for _, e := range m.ListMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to MetricStorageMock.List with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.ListMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterListCounter) < 1 {
		if m.ListMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to MetricStorageMock.List")
		} else {
			m.t.Errorf("Expected call to MetricStorageMock.List with params: %#v", *m.ListMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcList != nil && mm_atomic.LoadUint64(&m.afterListCounter) < 1 {
		m.t.Error("Expected call to MetricStorageMock.List")
	}
}

type mMetricStorageMockPing struct {
	mock               *MetricStorageMock
	defaultExpectation *MetricStorageMockPingExpectation
	expectations       []*MetricStorageMockPingExpectation

	callArgs []*MetricStorageMockPingParams
	mutex    sync.RWMutex
}

// MetricStorageMockPingExpectation specifies expectation struct of the MetricStorage.Ping
type MetricStorageMockPingExpectation struct {
	mock    *MetricStorageMock
	params  *MetricStorageMockPingParams
	results *MetricStorageMockPingResults
	Counter uint64
}

// MetricStorageMockPingParams contains parameters of the MetricStorage.Ping
type MetricStorageMockPingParams struct {
	ctx context.Context
}

// MetricStorageMockPingResults contains results of the MetricStorage.Ping
type MetricStorageMockPingResults struct {
	b1 bool
}

// Expect sets up expected params for MetricStorage.Ping
func (mmPing *mMetricStorageMockPing) Expect(ctx context.Context) *mMetricStorageMockPing {
	if mmPing.mock.funcPing != nil {
		mmPing.mock.t.Fatalf("MetricStorageMock.Ping mock is already set by Set")
	}

	if mmPing.defaultExpectation == nil {
		mmPing.defaultExpectation = &MetricStorageMockPingExpectation{}
	}

	mmPing.defaultExpectation.params = &MetricStorageMockPingParams{ctx}
	for _, e := range mmPing.expectations {
		if minimock.Equal(e.params, mmPing.defaultExpectation.params) {
			mmPing.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmPing.defaultExpectation.params)
		}
	}

	return mmPing
}

// Inspect accepts an inspector function that has same arguments as the MetricStorage.Ping
func (mmPing *mMetricStorageMockPing) Inspect(f func(ctx context.Context)) *mMetricStorageMockPing {
	if mmPing.mock.inspectFuncPing != nil {
		mmPing.mock.t.Fatalf("Inspect function is already set for MetricStorageMock.Ping")
	}

	mmPing.mock.inspectFuncPing = f

	return mmPing
}

// Return sets up results that will be returned by MetricStorage.Ping
func (mmPing *mMetricStorageMockPing) Return(b1 bool) *MetricStorageMock {
	if mmPing.mock.funcPing != nil {
		mmPing.mock.t.Fatalf("MetricStorageMock.Ping mock is already set by Set")
	}

	if mmPing.defaultExpectation == nil {
		mmPing.defaultExpectation = &MetricStorageMockPingExpectation{mock: mmPing.mock}
	}
	mmPing.defaultExpectation.results = &MetricStorageMockPingResults{b1}
	return mmPing.mock
}

// Set uses given function f to mock the MetricStorage.Ping method
func (mmPing *mMetricStorageMockPing) Set(f func(ctx context.Context) (b1 bool)) *MetricStorageMock {
	if mmPing.defaultExpectation != nil {
		mmPing.mock.t.Fatalf("Default expectation is already set for the MetricStorage.Ping method")
	}

	if len(mmPing.expectations) > 0 {
		mmPing.mock.t.Fatalf("Some expectations are already set for the MetricStorage.Ping method")
	}

	mmPing.mock.funcPing = f
	return mmPing.mock
}

// When sets expectation for the MetricStorage.Ping which will trigger the result defined by the following
// Then helper
func (mmPing *mMetricStorageMockPing) When(ctx context.Context) *MetricStorageMockPingExpectation {
	if mmPing.mock.funcPing != nil {
		mmPing.mock.t.Fatalf("MetricStorageMock.Ping mock is already set by Set")
	}

	expectation := &MetricStorageMockPingExpectation{
		mock:   mmPing.mock,
		params: &MetricStorageMockPingParams{ctx},
	}
	mmPing.expectations = append(mmPing.expectations, expectation)
	return expectation
}

// Then sets up MetricStorage.Ping return parameters for the expectation previously defined by the When method
func (e *MetricStorageMockPingExpectation) Then(b1 bool) *MetricStorageMock {
	e.results = &MetricStorageMockPingResults{b1}
	return e.mock
}

// Ping implements repositories.MetricStorage
func (mmPing *MetricStorageMock) Ping(ctx context.Context) (b1 bool) {
	mm_atomic.AddUint64(&mmPing.beforePingCounter, 1)
	defer mm_atomic.AddUint64(&mmPing.afterPingCounter, 1)

	if mmPing.inspectFuncPing != nil {
		mmPing.inspectFuncPing(ctx)
	}

	mm_params := MetricStorageMockPingParams{ctx}

	// Record call args
	mmPing.PingMock.mutex.Lock()
	mmPing.PingMock.callArgs = append(mmPing.PingMock.callArgs, &mm_params)
	mmPing.PingMock.mutex.Unlock()

	for _, e := range mmPing.PingMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.b1
		}
	}

	if mmPing.PingMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmPing.PingMock.defaultExpectation.Counter, 1)
		mm_want := mmPing.PingMock.defaultExpectation.params
		mm_got := MetricStorageMockPingParams{ctx}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmPing.t.Errorf("MetricStorageMock.Ping got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmPing.PingMock.defaultExpectation.results
		if mm_results != nil {
			return (*mm_results).b1
		}
		mmPing.t.Fatal("No results are set for the MetricStorageMock.Ping")

	}
	if mmPing.funcPing != nil {
		return mmPing.funcPing(ctx)
	}
	mmPing.t.Fatalf("Unexpected call to MetricStorageMock.Ping. %v", ctx)
	return
}

// PingAfterCounter returns a count of finished MetricStorageMock.Ping invocations
func (mmPing *MetricStorageMock) PingAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmPing.afterPingCounter)
}

// PingBeforeCounter returns a count of MetricStorageMock.Ping invocations
func (mmPing *MetricStorageMock) PingBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmPing.beforePingCounter)
}

// Calls returns a list of arguments used in each call to MetricStorageMock.Ping.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmPing *mMetricStorageMockPing) Calls() []*MetricStorageMockPingParams {
	mmPing.mutex.RLock()

	argCopy := make([]*MetricStorageMockPingParams, len(mmPing.callArgs))
	copy(argCopy, mmPing.callArgs)

	mmPing.mutex.RUnlock()

	return argCopy
}

// MinimockPingDone returns true if the count of the Ping invocations corresponds
// the number of defined expectations
func (m *MetricStorageMock) MinimockPingDone() bool {
	for _, e := range m.PingMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.PingMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterPingCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcPing != nil && mm_atomic.LoadUint64(&m.afterPingCounter) < 1 {
		return false
	}
	return true
}

// MinimockPingInspect logs each unmet expectation
func (m *MetricStorageMock) MinimockPingInspect() {
	for _, e := range m.PingMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to MetricStorageMock.Ping with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.PingMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterPingCounter) < 1 {
		if m.PingMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to MetricStorageMock.Ping")
		} else {
			m.t.Errorf("Expected call to MetricStorageMock.Ping with params: %#v", *m.PingMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcPing != nil && mm_atomic.LoadUint64(&m.afterPingCounter) < 1 {
		m.t.Error("Expected call to MetricStorageMock.Ping")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *MetricStorageMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockAddInspect()

			m.MinimockBulkAddInspect()

			m.MinimockGetInspect()

			m.MinimockListInspect()

			m.MinimockPingInspect()
			m.t.FailNow()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *MetricStorageMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *MetricStorageMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockAddDone() &&
		m.MinimockBulkAddDone() &&
		m.MinimockGetDone() &&
		m.MinimockListDone() &&
		m.MinimockPingDone()
}
